### PR TITLE
Restore 'Become BTC Staker guide' and FP guides

### PR DESCRIPTION
**Pull request by maurolacy**
Revert and move `btc-staking-testnet/` to `btc-staking-integration/`. These guides are needed for BTC staking integration guides on Notion.

(Partially) reverts commit 2bb482c24f2febdb313e20c81b650cf786ea0098.

### CODE REVIEW

**Review by gitferry — COMMENTED** [review]
The build fails probably because change in https://github.com/babylonchain/babylonchain.github.io/pull/85/files#diff-9a6a0fdafefb0eecffb77784bc94f5ad984062167b8bcb7c4a899c90f6f567e8L42. Sorry I didn't know this relates to integration

**Comment by maurolacy** [comment]
How to run the tests? Shouldn't they be part of CI?

**Comment by gitferry** [comment]
It's not part of CI. Devops need to run `yarn build` to generate static files and deploy

**Comment by gitferry** [comment]
@maurolacy I have submitted a fix to add the side bar back to make the build success. But I still noticed some legacy test related to `testnet-3` which we do not want to mislead users. Could you identify which recovered pages are not needed for integration?

**Comment by gitferry** [comment]
Just got an emergent request to recover the whole testnet-3 directory

**Comment by gitferry** [comment]
Done in #88.

**Pull request closed without merging**
