### PR TITLE
fix: Remove staking testnet-3 files and fix link err

### PR DESCRIPTION
**Pull request by gitferry**
It turned out that we have to remove `testnet-3` files otherwise compilation will fail with error:

`Docusaurus server-side rendering could not render static page with path /docs/user-guides/btc-staking-testnet/overview.`

This PR also fixed link errs

### CODE REVIEW

**Comment by maurolacy** [comment]
Hmm, we need the "Become BTC Staker" guide (https://docs.babylonchain.io/docs/user-guides/btc-staking-testnet/become-btc-staker), as it's linked in some of our (Notion) docs (https://www.notion.so/Instructions-for-integrating-with-Euphrates-0-2-0-51bbe3ff5c0840de84f35161fa943ba2)

Any workarounds?

**Comment by gitferry** [comment]
Hey, maybe we should have a separate page for integration instructions? The reason we removed the entire `btc-staking-testnet` dir is that it is for testnet-3 which is already down

**Comment by maurolacy** [comment]
OK, I'll create a PR for moving this to a `btc-staking-integration` folder instead. WDYT?

**Comment by maurolacy** [comment]
Done in #87.

**Pull request merged**
